version: "3.7"
services:
    agent-one:
        image: sst/sample-agent:latest
        command: ["sample-agent", "--target", "task-allocation-monitor:9090"]
    agent-two:
        image: sst/sample-agent:latest
        command: ["sample-agent", "--target", "task-allocation-monitor:9090"]
    task-allocation-monitor:
        image: sst/task-allocation-monitor:latest
        command: ["task-allocation-monitor", "-a", "0.0.0.0:9090", 
                                             "-t", "ALLOC_AUTH",
                                             "-t", "ENGINE_INFO",
                                             "-t", "PT_INFO",
                                             "-t", "SOLVER_RESULT",
                                             "-t", "ROLE_SWITCH",
                                             "-t", "SYNC_READY",
                                             "-t", "SYNC_TALK"]
